# Generated by Django 4.2.3 on 2023-07-17 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summery',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher_year',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 15, 44, 11, 771020, tzinfo=datetime.timezone.utc)),
        ),
    ]
