# Generated by Django 4.2.3 on 2023-07-17 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0002_book_summery_alter_book_publisher_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher_year',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 15, 44, 42, 493652, tzinfo=datetime.timezone.utc)),
        ),
    ]
