# Generated by Django 4.2.3 on 2023-07-17 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0003_alter_book_publisher_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher_year',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 15, 50, 23, 206505, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
