# Generated by Django 4.2.3 on 2023-07-17 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0004_alter_book_publisher_year_alter_publisher_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher_year',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 15, 52, 30, 711412, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='summery',
            field=models.TextField(blank=True, null=True),
        ),
    ]
