# Generated by Django 4.2.3 on 2023-07-20 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0005_alter_book_publisher_year_alter_book_summery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher_year',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 14, 36, 13, 684377, tzinfo=datetime.timezone.utc)),
        ),
    ]
