# Generated by Django 4.2.3 on 2023-07-20 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0006_alter_book_publisher_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher_year',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='phone_number',
            field=models.CharField(),
        ),
    ]
