# Generated by Django 4.2.3 on 2023-07-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0007_alter_book_publisher_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher_year',
            new_name='publish_year',
        ),
    ]
